### ISSUE TITLE
Plugin is not working with new version of Dremio (15.0)

### ISSUE THREAD

**Issue by militarpancho** [panoramichq/dremio-bigquery-connector#6]
Hi, I'm having some trouble with the latest version of the plugin after updating to dremio 15
**What happened**:

java.lang.NoClassDefFoundError: com/dremio/exec/store/jdbc/JdbcStoragePlugin$Config
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at com.dremio.exec.catalog.conf.ConnectionSchema.findInstantiator(ConnectionSchema.java:87)
	at com.dremio.exec.catalog.conf.ConnectionSchema.getSchema(ConnectionSchema.java:80)
	at com.dremio.exec.catalog.ConnectionReaderImpl.makeReader(ConnectionReaderImpl.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dremio.exec.catalog.ConnectionReader.of(ConnectionReader.java:69)
	at com.dremio.dac.daemon.DACDaemonModule.build(DACDaemonModule.java:375)
	at com.dremio.dac.daemon.DACDaemon.<init>(DACDaemon.java:186)
	at com.dremio.dac.daemon.DACDaemon.newDremioDaemon(DACDaemon.java:313)
	at com.dremio.dac.daemon.DACDaemon.newDremioDaemon(DACDaemon.java:321)
	at com.dremio.dac.daemon.DremioDaemon.main(DremioDaemon.java:145)

**How to reproduce it (as minimally and precisely as possible)**:
Install plugin with the latest version of Dremio 

**Details**:
- Dremio version (Help > About from the UI): 15.0.0
- Profile zip:
- server.log:

**Comment by militarpancho** [comment]
Fixed in #7
